version: '2'

services:
    drupal:
        build: .
        image: custom-drupal
        ports:
            - '8080:80'

    postgresql:
        image: postgres:12.1
        environment: 
            POSTGRES_DB: 'drupal'
            POSTGRES_USER: 'admin'
            POSTGRES_PASSWORD: '321admin'
        volumes: 
            - drupal-data:/var/lib/postgresql/data

volumes: 
    drupal-data: